baseURL = 'https://bsdnet.github.io'
languageCode = 'en-us'
title = 'Read, Practice, Summarize, Share'
theme = "PaperMod"
paginate = 5
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "The Infra Guy"
description = "A blog about infrastructure"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "Roy Yang"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

  [params.assets]
  favicon = "<link / abs url>"
  favicon16x16 = "<link / abs url>"
  favicon32x32 = "<link / abs url>"
  apple_touch_icon = "<link / abs url>"
  safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "Home"
  icon = "/apple-touch-icon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = true 
  title = "The Infra Guy"
  subtitle = "A blog about infrastructure develoopment"
  imageUrl = "<img location>"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Archive"
    url = "/archive"

    [[params.profileMode.buttons]]
    name = "Github"
    url = "https://github.com"

  [[params.socialIcons]]
  name = "envelope"
  url = "mailto:bsdnet@outlook.com"
  
  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/"
  
  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/cundongyang"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[[menu.main]]
identifier = "achieves"
name = "achives"
url = "/achieves/"
weight = 10

[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 10

