baseURL: https://bsdnet.github.io
languageCode: en-us
title: Learn, Practice, Summarize, Share
theme: PaperMod
paginate: 5
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
minify:
  disableXML: true
  minifyOutput: true
params:
  env: production
  title: The Infra Guy
  description: A blog about infrastructure
  keywords:
    - Blog
    - Portfolio
    - PaperMod
  author: Roy Yang
  images:
    - <link or path of image for opengraph, twitter-cards>
  DateFormat: January 2, 2006
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true
  assets:
    favicon: /favicon_io/favicon.ico
    favicon16x16: /favicon_io/favicon-16x16.png
    favicon32x32: /favicon_io/favicon-32x32.png
    apple_touch_icon: /favicon_io/apple-touch-icon.png
    safari_pinned_tab: <link / abs url>
  label:
    text: Home
    icon: /favicon_io/apple-touch-icon.png
    iconHeight: 35
  profileMode:
    enabled: true
    title: The Infra Guy
    subtitle: A blog about infrastructure development
    imageUrl: <img location>
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags
      - name: Archives
        url: archives
      - name: Github
        url: https://github.com
  socialIcons:
    - name: envelope
      url: mailto:bsdnet@outlook.com
    - name: github
      url: https://github.com/bsdnet
    - name: linkedin
      url: https://www.linkedin.com/in/cundongyang
    - name: discord
      url: https://www.discord.com/
  analytics:
    google:
      SiteVerificationTag: XYZabc
menu:
  main:
    - identifier: archives
      name: archives
      url: /archives/
      weight: 10
    - identifier: Search
      name: search
      url: /search/
      weight: 10
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 10
